# Generated by Django 6.0.4 on 2026-04-13 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_productevent_alter_productmedia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PetNabor', help_text='Displayed in email templates and the admin header.', max_length=100)),
                ('site_logo', models.ImageField(blank=True, help_text='Main site logo used in emails and frontend.', null=True, upload_to='site_settings/')),
                ('contact_email', models.EmailField(blank=True, default='', help_text='Primary contact email shown on the platform.', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When enabled, API returns 503 for non-admin requests.')),
                ('allow_vendor_registration', models.BooleanField(default=True, help_text='Toggle whether new vendors can register.')),
                ('allow_user_registration', models.BooleanField(default=True, help_text='Toggle whether new users can sign up.')),
                ('products_per_page', models.PositiveIntegerField(default=20, help_text='Default page size for product listings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_category', models.ForeignKey(blank=True, help_text='Category pinned to the top of the product feed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.categories')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
