# Generated by Django 6.0.4 on 2026-04-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_logo',
        ),
    ]
