# Generated by Django 6.0.3 on 2026-03-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_fcmdevice_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System Update'), ('login', 'New Login Detected'), ('security', 'Security Alert'), ('friend_request', 'New Friend Request'), ('friend_accept', 'Friend Request Accepted'), ('like', 'New Like on Post'), ('comment', 'New Comment'), ('mention', 'Mentioned in Post/Comment'), ('pet_reminder', 'Pet Care Reminder'), ('pet_match', 'Potential Pet Playmate Found'), ('vet_appointment', 'Vet Appointment Update'), ('meetup_invite', 'Meetup Invitation'), ('meetup_update', 'Meetup Details Changed'), ('event_reminder', 'Upcoming Pet Event'), ('order_status', 'Order Progress Update'), ('product_interest', 'Interest in Your Product'), ('service_booking', 'Service Booking Confirmed'), ('reward', 'Reward Available'), ('streak_bonus', 'Daily Streak Bonus'), ('referral_bonus', 'Referral Bonus Earned'), ('promotion', 'Special Promotion'), ('marketing', 'Marketing Message'), ('info', 'General Information')], default='info', max_length=20),
        ),
    ]
