# Generated by Django 6.0.4 on 2026-04-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_fcmdevice_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='low_balance_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='membership_expiry_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='new_order_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='weekly_performance_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System Update'), ('login', 'New Login Detected'), ('security', 'Security Alert'), ('friend_request', 'New Friend Request'), ('friend_accept', 'Friend Request Accepted'), ('post_like', 'New Like on Post'), ('story_like', 'New Like on Story'), ('post_comment', 'New Comment on Post'), ('story_comment', 'New Reply on Story'), ('post_mention', 'Mentioned in Post'), ('story_mention', 'Mentioned in Story'), ('otp', 'OTP'), ('password_reset', 'Password Reset'), ('message', 'New Message'), ('pet_reminder', 'Pet Care Reminder'), ('pet_match', 'Potential Pet Playmate Found'), ('vet_appointment', 'Vet Appointment Update'), ('meetup_invite', 'Meetup Invitation'), ('meetup_update', 'Meetup Details Changed'), ('event_reminder', 'Upcoming Pet Event'), ('order_status', 'Order Progress Update'), ('product_interest', 'Interest in Your Product'), ('service_booking', 'Service Booking Confirmed'), ('reward', 'Reward Available'), ('streak_bonus', 'Daily Streak Bonus'), ('referral_bonus', 'Referral Bonus Earned'), ('promotion', 'Special Promotion'), ('marketing', 'Marketing Message'), ('info', 'General Information'), ('membership_expiry', 'Membership Expiry Alert'), ('low_balance', 'Low Balance Alert'), ('new_order', 'New Order Notification'), ('weekly_report', 'Weekly Performance Report')], default='info', max_length=20),
        ),
    ]
