# Generated by Django 6.0.4 on 2026-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_price', models.DecimalField(decimal_places=2, default=9.99, help_text='Price for the one-time app verification badge.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to enable/disable the paid verification feature entirely.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verification Config',
                'verbose_name_plural': 'Verification Config',
            },
        ),
    ]
