# Generated by Django 6.0.4 on 2026-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationconfig',
            name='max_persona_attempts',
            field=models.IntegerField(default=3, help_text='Max times a user can attempt Persona ID verification before being permanently blocked.'),
        ),
    ]
