# Generated by Django 6.0.3 on 2026-03-24 18:42

import api.story.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='media_url',
        ),
        migrations.AddField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=api.story.models.Story.story_media_path),
        ),
    ]
