# Generated by Django 6.0.3 on 2026-03-17 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('USER', 'User'), ('POST', 'Post'), ('COMMENT', 'Comment'), ('STORY', 'Story'), ('BLOG', 'Blog'), ('MEETING', 'Meeting')], max_length=20)),
                ('target_id', models.UUIDField(db_index=True)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='report_repo_target__0bfa85_idx'), models.Index(fields=['is_resolved'], name='report_repo_is_reso_bf8fd5_idx')],
            },
        ),
    ]
