# Generated by Django 6.0.3 on 2026-03-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_notificationsettings_petprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
