# Generated by Django 6.0.3 on 2026-03-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_notificationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetProfile',
        ),
    ]
