# Generated by Django 6.0.3 on 2026-03-14 20:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_image_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
