# Generated by Django 6.0.3 on 2026-03-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_location_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patnabor', 'Patnabor'), ('patpal', 'Patpal'), ('vendor', 'Vendor'), ('admin', 'Admin')], db_index=True, default='patnabor', max_length=20),
        ),
    ]
