# Generated by Django 6.0.3 on 2026-03-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailverificationtoken_otpverification_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='users_email_token_76af91_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='users_email_user_id_0476c8_idx',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_type',
            field=models.CharField(choices=[('phone_signup', 'Phone Signup'), ('email_signup', 'Email Signup'), ('password_reset', 'Password Reset')], default='phone_signup', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
