# Generated by Django 6.0.4 on 2026-04-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_fix_location_point_lat_lng_swap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_patpal',
            new_name='is_petpal',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('petnabor', 'Petnabor'), ('petpal', 'Petpal'), ('vendor', 'Vendor'), ('admin', 'Admin')], default='petnabor', max_length=20),
        ),
    ]
