# Generated by Django 6.0.4 on 2026-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_is_patpal_user_is_petpal_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_app_verified',
            field=models.BooleanField(default=False, help_text='Paid persona verification badge'),
        ),
    ]
