# Generated by Django 6.0.4 on 2026-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_app_verified_at_user_is_app_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_identity_verified',
            field=models.BooleanField(default=False, help_text='Passed Persona ID KYC'),
        ),
        migrations.AddField(
            model_name='user',
            name='persona_inquiry_id',
            field=models.CharField(blank=True, help_text='Persona Inquiry ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='persona_status',
            field=models.CharField(default='pending', help_text='Persona Inquiry Status', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='persona_verification_attempts',
            field=models.IntegerField(default=0, help_text='Failed ID scan limits'),
        ),
    ]
