# Generated by Django 6.0.3 on 2026-03-24 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='TEXT', max_length=10)),
                ('media_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('bg_color', models.CharField(blank=True, help_text='CSS hex color or gradient token for text story background.', max_length=20, null=True)),
                ('privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS_ONLY', 'Friends Only')], default='PUBLIC', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('LIKE', 'Like'), ('LOVE', 'Love'), ('HAHA', 'Haha'), ('SAD', 'Sad'), ('ANGRY', 'Angry'), ('WOW', 'Wow')], default='LIKE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='story.story')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author', 'expires_at'], name='story_story_author__578528_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['privacy', 'expires_at'], name='story_story_privacy_e3861c_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at'], name='story_story_expires_a78f11_idx'),
        ),
        migrations.AddIndex(
            model_name='storyreaction',
            index=models.Index(fields=['story', 'user'], name='story_story_story_i_669749_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyreaction',
            unique_together={('story', 'user')},
        ),
        migrations.AddIndex(
            model_name='storyreply',
            index=models.Index(fields=['story', 'created_at'], name='story_story_story_i_82de8c_idx'),
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['story', 'viewer'], name='story_story_story_i_c3d426_idx'),
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['viewer', 'viewed_at'], name='story_story_viewer__7fc8ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together={('story', 'viewer')},
        ),
    ]
