# Generated by Django 6.0.3 on 2026-03-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='post_report_target__dfcba0_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='post_report_is_reso_c415cd_idx',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
