# Generated by Django 6.0.3 on 2026-03-17 20:57

import api.post.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_report_post_report_target__dfcba0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='replies_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='medium_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=api.post.models.post_media_path),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='thumbnail_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=api.post.models.post_media_path),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_deleted', 'created_at'], name='post_post_is_dele_5cab69_idx'),
        ),
    ]
