"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import firebase_admin
from firebase_admin import credentials

from dotenv import load_dotenv
import os

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = (
    os.getenv("DJANGO_ALLOWED_HOSTS").split(",")
    if os.getenv("DJANGO_ALLOWED_HOSTS")
    else []
)

# CSRF configuration
CSRF_TRUSTED_ORIGINS = (
    os.getenv("CSRF_TRUSTED_ORIGINS").split(",")
    if os.getenv("CSRF_TRUSTED_ORIGINS")
    else []
) + ["http://localhost:8001", "http://127.0.0.1:8001"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    # django-unfold must come BEFORE django.contrib.admin
    "unfold",
    "unfold.contrib.filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    # Third-party apps
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    # Local apps
    "api.users",
    "api.notifications",
    "api.pet",
    "api.friends",
    "api.messaging",
    "api.post",
    "api.report",
    "api.story",
    "api.blog",
    "api.meeting",
    "api.referral",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "api.users.middleware.UpdateLastActiveMiddleware",
    "api.users.middleware.VerificationEnforcementMiddleware",
]

CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"

# ──────────────────────────────────────────────
# Cache (Redis)
# ──────────────────────────────────────────────

REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/1")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "db": "1",
        },
        "KEY_PREFIX": "patnabor",
        "TIMEOUT": 300,  # default 5-minute TTL
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL", "redis://redis:6379/1")],
        },
    },
}

AUTH_USER_MODEL = "users.User"


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
        "TEST": {
            "NAME": "test_petnabor_db_new",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ──────────────────────────────────────────────
# django-unfold Admin Configuration
# ──────────────────────────────────────────────

UNFOLD = {
    "SITE_TITLE": "PetNabor Admin",
    "SITE_HEADER": "PetNabor",
    "SITE_SUBHEADER": "Social Media Dashboard",
    "SITE_URL": "/",
    "SITE_SYMBOL": "pets",          # Google Material Symbol
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "ENVIRONMENT": "api.users.admin_utils.environment_callback",
    "DASHBOARD_CALLBACK": "api.users.admin_utils.dashboard_callback",
    "BORDER_RADIUS": "8px",
    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark": "156 163 175",
            "default-light": "17 24 39",
            "default-dark": "243 244 246",
        },
        "primary": {
            "50": "245 243 255",
            "100": "237 233 254",
            "200": "221 214 254",
            "300": "196 181 253",
            "400": "167 139 250",
            "500": "139 92 246",
            "600": "124 58 237",
            "700": "109 40 217",
            "800": "91 33 182",
            "900": "76 29 149",
            "950": "46 16 101",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": False,
                "items": [
                    {
                        "title": "Overview",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "User Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/users/user/",
                        "badge": "api.users.admin_utils.user_count_badge",
                    },
                    {
                        "title": "Profiles",
                        "icon": "manage_accounts",
                        "link": "/admin/users/profile/",
                    },
                    {
                        "title": "OTP Verifications",
                        "icon": "verified",
                        "link": "/admin/users/otpverification/",
                    },
                ],
            },
            {
                "title": "Content",
                "separator": True,
                "items": [
                    {
                        "title": "Posts",
                        "icon": "article",
                        "link": "/admin/post/post/",
                    },
                    {
                        "title": "Stories",
                        "icon": "auto_stories",
                        "link": "/admin/story/story/",
                    },
                    {
                        "title": "Blogs",
                        "icon": "rss_feed",
                        "link": "/admin/blog/blog/",
                    },
                    {
                        "title": "Hashtags",
                        "icon": "tag",
                        "link": "/admin/post/hashtag/",
                    },
                ],
            },
            {
                "title": "Pets",
                "separator": True,
                "items": [
                    {
                        "title": "Pet Profiles",
                        "icon": "pets",
                        "link": "/admin/pet/petprofile/",
                    },
                ],
            },
            {
                "title": "Social",
                "separator": True,
                "items": [
                    {
                        "title": "Friend Requests",
                        "icon": "person_add",
                        "link": "/admin/friends/friendrequest/",
                    },
                    {
                        "title": "Friendships",
                        "icon": "group",
                        "link": "/admin/friends/friendship/",
                    },
                    {
                        "title": "User Blocks",
                        "icon": "block",
                        "link": "/admin/friends/userblock/",
                    },
                    {
                        "title": "Meetings",
                        "icon": "event",
                        "link": "/admin/meeting/meeting/",
                    },
                ],
            },
            {
                "title": "Moderation",
                "separator": True,
                "items": [
                    {
                        "title": "Reports",
                        "icon": "flag",
                        "link": "/admin/report/report/",
                        "badge": "api.users.admin_utils.pending_reports_badge",
                    },
                ],
            },
            {
                "title": "Messaging",
                "separator": True,
                "items": [
                    {
                        "title": "Chat Threads",
                        "icon": "forum",
                        "link": "/admin/messaging/chatthread/",
                    },
                    {
                        "title": "Messages",
                        "icon": "chat",
                        "link": "/admin/messaging/message/",
                    },
                ],
            },
            {
                "title": "Notifications",
                "separator": True,
                "items": [
                    {
                        "title": "Sent Notifications",
                        "icon": "notifications",
                        "link": "/admin/notifications/notifications/",
                    },
                    {
                        "title": "FCM Devices",
                        "icon": "devices",
                        "link": "/admin/notifications/fcmdevice/",
                    },
                    {
                        "title": "Notification Settings",
                        "icon": "tune",
                        "link": "/admin/notifications/notificationsettings/",
                    },
                ],
            },
            {
                "title": "Referral System",
                "separator": True,
                "items": [
                    {
                        "title": "Settings",
                        "icon": "settings",
                        "link": "/admin/referral/referralsettings/",
                    },
                    {
                        "title": "Wallets",
                        "icon": "wallet",
                        "link": "/admin/referral/referralwallet/",
                    },
                    {
                        "title": "Transactions",
                        "icon": "receipt_long",
                        "link": "/admin/referral/referraltransaction/",
                    },
                ],
            },
        ],
    },
    "TABS": [],
}


# Media
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# REST Framework configuration

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "otp_send": "5/hour",
        "otp_verify": "10/hour",
        "auth_login": "20/hour",
        "messaging_send": "5000/hour",
        "post_like": "60/minute",
        "post_comment": "30/minute",
        "post_save": "60/minute",
    },
    "EXCEPTION_HANDLER": "api.users.exception_handler.custom_exception_handler",
}

# Swagger / OpenAPI settings
SPECTACULAR_SETTINGS = {
    "TITLE": "PetNabor API",
    "DESCRIPTION": "Interactive API documentation for the PetNabor application.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/",
    "SCHEMA_PATH_PREFIX_TRIM": True,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    "ENUM_NAME_OVERRIDES": {
        "PrivacyEnum": "api.post.models.Post.Privacy",
        "MediaTypeEnum": "api.post.models.PostMedia.MediaType"
    },
}

# SimpleJWT Configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

FIREBASE_CREDENTIALS = os.path.join(BASE_DIR, "firebase-credentials.json")


def initialize_firebase():
    if not firebase_admin._apps:
        cred = credentials.Certificate(FIREBASE_CREDENTIALS)
        firebase_admin.initialize_app(cred)


initialize_firebase()


# ──────────────────────────────────────────────
# Twilio Configuration (Phone OTP)
# ──────────────────────────────────────────────

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER", "")


# ──────────────────────────────────────────────
# Email Configuration (Gmail SMTP)
# ──────────────────────────────────────────────

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = os.getenv("EMAIL_PORT", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("EMAIL_HOST_USER", "")


# ──────────────────────────────────────────────
# OTP Configuration
# ──────────────────────────────────────────────

OTP_LENGTH = int(os.getenv("OTP_LENGTH", "4"))
OTP_EXPIRY_MINUTES = int(os.getenv("OTP_EXPIRY_MINUTES", "5"))
OTP_MAX_ATTEMPTS = int(os.getenv("OTP_MAX_ATTEMPTS", "5"))

# Email verification token expiry (in hours)
EMAIL_VERIFICATION_EXPIRY_HOURS = int(
    os.getenv("EMAIL_VERIFICATION_EXPIRY_HOURS", "24")
)


# ──────────────────────────────────────────────
# CORS Configuration
# ──────────────────────────────────────────────

CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = (
    os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if os.getenv("CORS_ALLOWED_ORIGINS")
    else []
)


# ──────────────────────────────────────────────
# Post / Media Processing Settings
# ──────────────────────────────────────────────

# Max upload size in bytes (default 50 MB)
POST_MEDIA_MAX_SIZE_BYTES = int(os.getenv("POST_MEDIA_MAX_SIZE_MB", "50")) * 1024 * 1024

# Main image max dimensions (width, height)
POST_IMAGE_MAX_DIM = (1920, 1080)

# Medium variant dimensions
POST_IMAGE_MEDIUM_DIM = (800, 800)

# Thumbnail dimensions
POST_IMAGE_THUMB_DIM = (400, 400)

# WebP quality for main + medium image
POST_IMAGE_QUALITY = int(os.getenv("POST_IMAGE_QUALITY", "85"))

# WebP quality for thumbnail
POST_THUMB_QUALITY = int(os.getenv("POST_THUMB_QUALITY", "75"))

# Allowed file extensions for post media uploads
POST_ALLOWED_EXTENSIONS = {"jpg", "jpeg", "png", "webp", "gif", "mp4", "mov"}

# Allowed MIME types (server-side validation — spoof-resistant)
POST_ALLOWED_IMAGE_MIME = {"image/jpeg", "image/png", "image/webp", "image/gif"}
POST_ALLOWED_VIDEO_MIME = {"video/mp4", "video/quicktime"}
POST_ALLOWED_MIME_TYPES = POST_ALLOWED_IMAGE_MIME | POST_ALLOWED_VIDEO_MIME


# ──────────────────────────────────────────────
# Story Settings
# ──────────────────────────────────────────────

# How many hours a story remains visible after posting (default 24 h)
STORY_EXPIRY_HOURS: int = int(os.getenv("STORY_EXPIRY_HOURS", "24"))
