# Generated by Django 6.0.4 on 2026-04-22 19:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0002_alter_meeting_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Platform commission percentage taken from each tip (e.g. 20.00 = 20%).', max_digits=5)),
                ('minimum_tip_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Minimum tip amount in USD.', max_digits=8)),
                ('maximum_tip_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Maximum tip amount in USD.', max_digits=8)),
                ('minimum_withdrawal_amount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum withdrawal amount in USD.', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tip Settings',
                'verbose_name_plural': 'Tip Settings',
            },
        ),
        migrations.CreateModel(
            name='StripeConnectAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_account_id', models.CharField(help_text='Stripe Express Account ID (acct_xxx).', max_length=255, unique=True)),
                ('is_onboarding_complete', models.BooleanField(default=False, help_text="True once the user has completed Stripe's KYC onboarding.")),
                ('is_charges_enabled', models.BooleanField(default=False, help_text='True when Stripe reports charges_enabled on the account.')),
                ('is_payouts_enabled', models.BooleanField(default=False, help_text='True when Stripe reports payouts_enabled on the account.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_connect_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Connect Account',
                'verbose_name_plural': 'Stripe Connect Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total tip amount charged to tipper (USD).', max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Commission % applied at the time this tip was created (snapshot).', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Platform commission amount in USD.', max_digits=10)),
                ('recipient_amount', models.DecimalField(decimal_places=2, help_text='Amount received by recipient after commission deduction.', max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(blank=True, help_text='The meeting this tip is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='meeting.meeting')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips_received', to=settings.AUTH_USER_MODEL)),
                ('tipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipper', 'status'], name='tip_tip_tipper__ee0255_idx'), models.Index(fields=['recipient', 'status'], name='tip_tip_recipie_e47595_idx'), models.Index(fields=['status', 'created_at'], name='tip_tip_status_8de9ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Withdrawal amount in USD.', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('stripe_payout_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connect_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='tip.stripeconnectaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tip Withdrawal',
                'verbose_name_plural': 'Tip Withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='tip_tipwith_user_id_caea7b_idx')],
            },
        ),
    ]
