# Generated by Django 6.0.4 on 2026-04-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Transfer ID — set when a held tip is released to the recipient.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('held', 'Held — Awaiting Recipient Account'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
