# Generated by Django 6.0.4 on 2026-04-13 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('vendor', '0002_vendorplan_alter_vendor_plan_vendorsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('IMPRESSION', 'Impression')], db_index=True, max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=128, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Product Event',
                'verbose_name_plural': 'Product Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productmedia',
            options={'verbose_name': 'Product Media', 'verbose_name_plural': 'Product Media'},
        ),
        migrations.RenameField(
            model_name='productmedia',
            old_name='media_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_category_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor'], name='product_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='product_is_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_media_per_product'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='product.product'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['product'], name='productevent_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['event_type'], name='productevent_type_idx'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['created_at'], name='productevent_created_idx'),
        ),
    ]
