# Generated by Django 6.0.3 on 2026-03-14 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['sender', 'status'], name='friends_fri_sender__161e45_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['receiver', 'status'], name='friends_fri_receive_79aa1f_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user1'], name='friends_fri_user1_i_02c237_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user2'], name='friends_fri_user2_i_788741_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocker'], name='friends_use_blocker_37042f_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocked_user'], name='friends_use_blocked_48626f_idx'),
        ),
    ]
