# Generated by Django 6.0.3 on 2026-03-15 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendrequest_friends_fri_sender__161e45_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='friendship',
            name='friends_fri_user1_i_02c237_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='friends_fri_user2_i_788741_idx',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user1',
            new_name='initiator',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user2',
            new_name='receiver',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('initiator', 'receiver')},
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['initiator'], name='friends_fri_initiat_beeccc_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['receiver'], name='friends_fri_receive_aec1fa_idx'),
        ),
    ]
