# Generated by Django 6.0.3 on 2026-03-15 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_remove_friendship_friends_fri_user1_i_02c237_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='friendship',
            name='friends_fri_initiat_beeccc_idx',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='initiator',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('sender', 'receiver')},
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['sender'], name='friends_fri_sender__3769ce_idx'),
        ),
    ]
